spring.application.name=jobservice
spring.datasource.url=jdbc:postgresql://localhost:5432/jobservice
spring.datasource.username=postgres
spring.datasource.password=Sheik444

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port:8088