# Application Name
spring.application.name=jobservice

# Server Port
server.port=8088

# PostgreSQL DB Config
spring.datasource.url=jdbc:postgresql://localhost:5432/jobservice
spring.datasource.username=postgres
spring.datasource.password=Sheik444

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true


# Kafka Configuration

spring.kafka.bootstrap-servers=localhost:9092

# Producer Config
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Consumer 
spring.kafka.consumer.group-id=job-group
spring.kafka.consumer.auto-offset-reset=earliest